/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.github.smmayank.leetcode;

import java.util.logging.Logger;

public class App {

    private static final String GREETING_MESSAGE = "Hello World!";

    private static final Logger LOGGER = Logger.getLogger(App.class.getSimpleName());

    public static void main(String[] args) {
        LOGGER.info(new App().getGreeting());
    }

    public String getGreeting() {
        return GREETING_MESSAGE;
    }
}
